repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.3
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus" ]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: ['--line-length=79']

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
#        args: [ '--ignore=E501' ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-byte-order-marker
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
